spring:
  application:
    name: cursify
  datasource:
    #url: jdbc:mysql://root:UnXJ55bdoAGHecNiQOwb@containers-us-west-59.railway.app:7699/railway
    url: jdbc:mysql://localhost:3306/cursify
    username: root
    #password: UnXJ55bdoAGHecNiQOwb
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  media:
    location: mediafiles
server:
  port: 8080
